[package]
name = "button_pi"
version = "0.1.0"
authors = ["jake"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns-lookup = "1.0.3"
gpio-cdev = "0.2"